### ISSUE TITLE
Install issue - unable to load addon.xml

### ISSUE THREAD

**Issue by harvybob** [hyperion-project/hyperion.control#26]
Hi All,
Thanks for the work on this, I had hyperion running on Kodi - Leia, but with recent updates the screen scraping issue has broken it. 

I have come across this repo and code, and am trying to install but seeing this error in my kodi.log:

```
2023-08-02 11:55:09.110 T:547     debug <general>: CAddonInstaller: installing from zip '/home/osmc/hyperion.control-20.0.0.zip'
2023-08-02 11:55:09.112 T:547     error <general>: CAddonInfoBuilder::Generate: Unable to load 'zip://%2fhome%2fosmc%2fhyperion.control-20.0.0.zip/hyperion.control-20.0.0/addon.xml', Line 0
                                                   Failed to open file

```

The file has been downloaded to /home/osmc/
Looking at the zip file, the addon.xml is in the folder, its nested within script.service.hyperion-control

Steps taken to install are:
Reboot of OSMC ( personal choice to restart before update)
select addons
install from zip
select local device (note I have also tried from smb location)
error above comes up in the log, and banner on screen to say install failed.

Not sure if this is an issue with my setup/config? are there any pre-requirements to be installed?

If so, any guidance on what to change? any pre installations that are required?

Env is:
RPI2 - OSMC 2023-07-1 which I think it is 20?
Hyperion - 2.0.15

**Comment by Lord-Grey** [comment]
Due to the fact that we are now publishing also to the official Kodi repository, the structure of the source file had to change.
I added a pure add-on package to the release now.
Please check, if that works for you.

**Comment by harvybob** [comment]
Thanks - do you know when it will be included in the official kodi repo?

**Comment by Lord-Grey** [comment]
I already see it in the official repository for Nexus
https://kodi.tv/addons/nexus/script.service.hyperion-control/

**Comment by harvybob** [comment]
Apologies - yes I can see it now!
Installed (both ways) successfully - I just misunderstood what it did! I was looking for screen capturing for videos which is currently broken and thought this may be a fix!

**Comment by Lord-Grey** [comment]
I guess you are looking for this: https://github.com/hyperion-project/hyperion.kodi
We are on our way to have it published too.

**Comment by harvybob** [comment]
Yep that is what I am after - but waiting for the RPI Fix! Thanks for the work on it!

**Comment by Lord-Grey** [comment]
Maybe you can still give it a try?
Just to see, if the problems is only related to specific devices.
The bug has lately been tagged to Kodi 21 which is further down the road…
